config/routes.rb
Battle::Application.routes.draw do
  
  

  resources :feedbacks, :only => [:new, :create] do
    collection do
      get :thank_you
    end  
  end  

  class ForRedirectFromGeneralPage 
    def self.matches?(request)
      return false unless Buttle.where(:published => true).first;
      return true
    end  
  end  
  constraints ForRedirectFromGeneralPage do
    match "/" => redirect {| p,request | "/buttles/#{Buttle.in_general_page.id}" }
  end  
  match "/" => "buttles#index"

  resources :buttles  

  namespace :myadmin do
    match "/" => "index#index"
    resources :buttles
    resources :feedbacks do
      member do 
        post :to_read_message
      end  
      collection do
        get :massmove
      end  
    end  

    resources :lots do
      collection do       
        get :one_lot
      end
      member do 
      end  
    end  

    resources :options do
      member do
        post :quick_update
      end  
      collection do
        get :massmove
      end  
    end  

    get '/votes' => 'votes#all'

  end  #myadmin
      

  resources :votes, :only => :new  
    
  match "/home", :to => "pages#home"
  

  root :to => "pages#home"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :email, :message, :name, :theme

  scope :no_read, where(:read => false)
  scope :yes_read, where(:read => true)
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    #@feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to feedbacks_path, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/application_controller.rb
class Myadmin::ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate#:check_access
  layout 'myadmin'



  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      md5_of_password = Digest::MD5.hexdigest(password)
      username == 'admin' && password == 'admin'#md5_of_password == 'a86838dae048198de7487400d109bfd3'
    end  	
  end	
  #def check_access
  #	true
  #end	
end

app/controllers/myadmin/buttles_controller.rb
class Myadmin::ButtlesController < Myadmin::ApplicationController
  # GET /buttles
  # GET /buttles.json
  def index
    @buttles = Buttle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buttles }
    end
  end

  # GET /buttles/1
  # GET /buttles/1.json
  def show
    @buttle = Buttle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buttle }
    end
  end

  # GET /buttles/new
  # GET /buttles/new.json
  def new
    @buttle = Buttle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buttle }
    end
  end

  # GET /buttles/1/edit
  def edit
    @buttle = Buttle.find(params[:id])
    @lots = Lot.all
  end

  # POST /buttles
  # POST /buttles.json
  def create
    @buttle = Buttle.new(params[:buttle])

    respond_to do |format|
      if @buttle.save
        format.html { redirect_to myadmin_buttles_path, notice: 'Buttle was successfully created.' }
        format.json { render json: @buttle, status: :created, location: @buttle }
      else
        format.html { render action: "new" }
        format.json { render json: @buttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buttles/1
  # PUT /buttles/1.json
  def update
    @buttle = Buttle.find(params[:id])

    respond_to do |format|
      if @buttle.update_attributes(params[:buttle])
        format.html { redirect_to myadmin_buttles_path, notice: 'Buttle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buttles/1
  # DELETE /buttles/1.json
  def destroy
    @buttle = Buttle.find(params[:id])
    @buttle.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_buttles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/feedbacks_controller.rb
class Myadmin::FeedbacksController < Myadmin::ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    #@feedbacks = Feedback.all
    @feedbacks = Feedback.no_read

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  def thank_you
    #@feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end  

  def to_read_message
    feedback_item = Feedback.find(params[:id])
    feedback_item.update_attribute(:read, true)
    render :json => {:result => "ok"}
  end

  def massmove
    Feedback.all.map{|item|item.update_attribute(:read, true)} if params[:move] == "read"
    Feedback.all.map{|item|item.update_attribute(:read, false)} if params[:move] == "not_read"

    respond_to do |format|
      format.html { redirect_to myadmin_feedbacks_url}
    end  

  end  

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to myadmin_thank_you_feedbacks_path, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/index_controller.rb
class Myadmin::IndexController < Myadmin::ApplicationController
  def index

  end	


end	

app/controllers/myadmin/lots_controller.rb
class Myadmin::LotsController < Myadmin::ApplicationController
  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lots }
    end
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @lot }
    end
  end

  # GET /lots/new
  # GET /lots/new.json
  def new
    @lot = Lot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @lot }
    end
  end

  # GET /lots/1/edit
  def edit
    @lot = Lot.find(params[:id])
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(params[:lot])

    respond_to do |format|
      if @lot.save
        format.html { redirect_to myadmin_lots_path, :notice => 'Lot was successfully created.' }
        format.json { render :json => @lot, :status => :created, :location => @lot }
      else
        format.html { render :action => "new" }
        format.json { render :json => @lot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lots/1
  # PUT /lots/1.json
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to myadmin_lots_path, :notice => 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @lot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_lots_url }
      format.json { head :no_content }
    end
  end

  def one_lot
    @lots = Lot.all
    @opponent_number = params[:opponent]
    respond_to do |format|
      format.html {}
      format.js {}
    end  
  end  

end

app/controllers/myadmin/options_controller.rb
class Myadmin::OptionsController < Myadmin::ApplicationController
  # GET /options
  # GET /options.json
  def index
    @options = Option.all
    @ip = request.remote_ip
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /options/1/quick_update
  def quick_update
    @option = Option.find_by_id(params[:id])
    if @option
      @option.update_attributes(params[:option])
    else
      @option = Option.create(params[:option])   
    end  


    respond_to do |format|
      if @option
        format.json { render json: @option.id }        
      else
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end  
    end      


  end  


  def massmove
    if params[:move] == "delete"
      Option.delete_all
      respond_to do |format| 
        format.html {redirect_to myadmin_options_path }
      end  
    end  
  end  

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_options_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/votes_controller.rb
class Myadmin::VotesController < Myadmin::ApplicationController

  def all

    @all_votes = Vote.all
    respond_to do |format|
      format.html
    end  

  end  

end	

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/myadmin/feedbacks/_form.html.erb
<%= form_for(@feedback, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
      <%= f.label "Имя", :class => "control-label",  :for=>"inputEmail" %>
      <div class="controls">
        <%= f.text_field :name, :id=>"inputPassword", :placeholder=>"Представьтесь" %>
      </div>
  </div>

  <div class="control-group">
      <%= f.label "E-mail", :class => "control-label",  :for=>"inputEmail" %>
      <div class="controls">
        <%= f.text_field :email, :id=>"inputPassword", :placeholder=>"Ваше мыло?" %>
      </div>
  </div>



  <div class="control-group">
      <%= f.label "Сообщение", :class => "control-label",  :for=>"inputEmail" %>
      <div class="controls">
        <%= f.text_area :message, :id=>"inputPassword", :placeholder=>"Ну как вам..." %>
      </div>
  </div>    

  <div class="control-group">
      <div class="controls">
        <%= f.submit "Отправить отзыв",:class => "btn" %>
      </div>
  </div>  


 
<% end %>

app/views/myadmin/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/myadmin/feedbacks/index.html.erb
<div class="row-fluid center-elem">
<h2>Список фидбека</h2>
</div>

<div class="row-fluid">
  <div class="span3 offset9">
    <div class="btn-group">
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        Массввые действия
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Поместить как прочитанные",  massmove_myadmin_feedbacks_path(:move => "read") %></li>
        <li><%= link_to "Поместить как непрочитанные",  massmove_myadmin_feedbacks_path(:move => "not_read") %></li>
        <!-- dropdown menu links -->
      </ul>
    </div>
  </div>
</div>  

<% @feedbacks.each do |feedback| %>
<div class="row-fluid">
<blockquote>	
  <div class="row-fluid">
  	<div class="span6">
  		<p class="label label-info"> Имя: </p>
        <span class="lead">
  		<%=feedback.name %>
  		</span>  		  
  	</div>	
  </div>
  <div class="row-fluid">
  	<div class="span6 ">
  		<p class="label label-info">
  		Мыло: </p> 
  		<span class="lead">
  		<%=feedback.email %>
  		</span>
  	</div>	
  </div>

<style>
.read_feedback_message {
  cursor: pointer;
}
</style>

<script>
$(function(){
  $(".read_feedback_message").mouseenter(function(){
    $(this).css("border","solid 2px lightsteelblue");
  });
  $(".read_feedback_message").mouseleave(function(){
    $(this).css("border","solid 0px lightsteelblue");
  })  
  $(".read_feedback_message").click(function(){    
    id = $(this).attr("id");
    //$(this).html("123");
    _this = $(this)
    $.ajax({
        type: "POST",
        url: "<%= to_read_message_myadmin_feedback_path(':id') %>".replace(":id", id),
        success: function(data){
          if (data.result == 'ok') {
            _this.html('<p class="label label-info">Прочитано?: </p> <span class="lead">Да</span>');
          } else {
            alert('Что-то не так');
          }
        }
      });
  })
})
</script>  

  <div class="row-fluid">
    <div class="span6 read_feedback_message" id="<%= feedback.id %>">
      <% if feedback.read %>
        <p class="label label-info">Прочитано?: </p> 
        <span class="lead">Да</span>
      <% else %>
        <p class="label label-important">Прочитано?: </p> 
        <span class="lead">Нет</span>      
      <% end %>
    </div>  
  </div>  

  <br/>
  <div class="row-fluid">
  	<div class="span12" style="border: 4px solid lightsteelblue; margin: 5px; padding: 10px " >
     <!-- <p class="label label-info">Сообщение:</p> -->
      <small>
      <%=feedback.message %>
  	  </small>
  	</div>	
  </div>
  <br/>

</blockquote>  	
  <div class="row-fluid">
    <div class="span3 offset2">
      [<%= link_to "Открыть", myadmin_feedback_path(feedback) %>] 
    </div>  
    <div class="span3">
      [<%= link_to  "Обновить", myadmin_feedback_path(feedback), :method => :put %>]  
    </div>  
    <div class="span3">
      [<%= link_to "Удалить", myadmin_feedback_path(feedback), :method => :delete %>]
    </div>          
  </div>
</div>  		

<% end %>

app/views/myadmin/feedbacks/new.html.erb
<h2>Вопросы/Жалобы/Предложения</h2>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/myadmin/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @feedback.name %>
</p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>Theme:</b>
  <%= @feedback.theme %>
</p>

<p>
  <b>Message:</b>
  <%= @feedback.message %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/myadmin/feedbacks/thank_you.html.erb
<div style="text-align: center">
<h1>Спасибо!</h1>
<%= link_to("Написать еще один отзыв", new_feedback_path, :class => "btn btn-block btn-large") %>
</div>