config/routes.rb
Battle::Application.routes.draw do
  
  

  resources :feedbacks, :only => [:new, :create] do
    collection do
      get :thank_you
    end  
  end  

  class ForRedirectFromGeneralPage 
    def self.matches?(request)
      return false unless Buttle.where(:published => true).first;
      return true
    end  
  end  
  constraints ForRedirectFromGeneralPage do
    match "/" => redirect {| p,request | "/buttles/#{Buttle.in_general_page.id}" }
  end  
  match "/" => "buttles#index"

  resources :buttles  

  namespace :myadmin do
    match "/" => "index#index"
    resources :buttles
    resources :feedbacks do
      member do 
        post :to_read_message
      end  
      collection do
        get :massmove
      end  
    end  

    resources :lots do
      collection do       
        get :one_lot
      end
      member do 
      end  
    end  

    resources :options do
      member do
        post :quick_update
      end  
      collection do
        get :massmove
      end  
    end  

    get '/votes' => 'votes#all'

  end  #myadmin
      

  resources :votes, :only => :new  
    
  match "/home", :to => "pages#home"
  

  root :to => "pages#home"

end

app/views/shared/_admin_head.html.erb
<%
# named block
page_lots = "Лоты"
page_buttles = "Битвы"
page_feedbacks = "Фидбек пользователей"
page_root = "На сайт"
page_options_name = "Опции"
page_votes_name = "Голоса"

%>

<div class="navigation_admin">
<ul class="nav nav-pills pull-right">
  <li <% if current_page? myadmin_lots_path %> class="active" <% end %>     >
  	<%= 
  	  link_to_unless_current(page_lots, myadmin_lots_path) do 
  	  	link_to(page_lots, "#")
  	  end	
  	%>
  </li>
  <li  <% if current_page? myadmin_buttles_path %> class="active" <% end %> >
  	<%= 
  	  link_to_unless_current(page_buttles, myadmin_buttles_path) do 
  	  	link_to(page_buttles, "#")
  	  end	
  	%>
  </li>
  <li  <% if current_page? myadmin_feedbacks_path %> class="active" <% end %> >
    <%= 
      link_to_unless_current(page_feedbacks, myadmin_feedbacks_path) do 
        link_to(page_feedbacks, "#")
      end 
    %>
  </li>
  <li  <% if current_page? myadmin_options_path %> class="active" <% end %> >
    <%= 
      link_to_unless_current(page_options_name, myadmin_options_path) do 
        link_to(page_options_name, "#")
      end 
    %>
  </li>

  <li  <% if current_page? myadmin_votes_path %> class="active" <% end %> >
    <%= 
      link_to_unless_current(page_votes_name, myadmin_votes_path) do 
        link_to(page_votes_name, "#")
      end 
    %>
  </li>

  <li  <% if current_page? root_path %> class="active" <% end %> >
    <%= 
      link_to_unless_current(page_root, root_path) do 
        link_to(page_root, "#")
      end 
    %>
  </li>  


  <li></li>
</ul>
</div>
<div class="clear"></div>

app/views/shared/_head_general.html.erb
	<div class="row-fluid">
		<div class="span12">
			<div class="row-fluid">
				<div class="span12 offset0">
					<!-- <img href="#" class="thumbnail"> -->
					<p style="text-align:center">
						<% logo = image_tag("decor/Dva_samuraya.png", :alt=>"Sample app", :class=>"img-rounded", :width=>"130")%>
						<%= link_to logo, root_path, :class => "thumbnail_null" %>
					</p>
				</div>	
		

			</div>
		</div>
	</div>

app/views/shared/_head_script_social_vote.html.erb
<script>


vkontakte_obj.shares_url = "<%= shares_url %>";
facebook_obj.shares_url  = "<%= shares_url %>";
twitter_obj.shares_url   = "<%= shares_url %>";
//Секция инициализации

function init_popover() {

  $("#voice_left").popover({ title: 'Воспользуйтесь соц.сетью', 
  				html: 'true', 
  				placement: 'left' ,
  				content: soc_v_left+soc_t_left+soc_f_left });	
  
  $("#voice_right").popover({ title: 'Воспользуйтесь соц.сетью', 
  				html: 'true', 
  				placement: 'right' ,
  				content: soc_v_right+soc_t_right+soc_f_right });	

}


$(function(){
	vkontakte_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );	

	vkontakte_obj.elem_view= $('#vk_lot_left');

	twitter_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );

	twitter_obj.elem_view= $('#tw_lot_left');	

	facebook_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );

	facebook_obj.elem_view= $('#fb_lot_left');	


	soc_f_left = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Facebook.png"  class="share_fb" id="share_fb_left" />';
	soc_f_right = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Facebook.png" class="share_fb" id="share_fb_right" />';
	soc_t_left  = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Twitter.png" class="share_tw" id="share_tw_left" />';
	soc_t_right = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Twitter.png" class="share_tw" id="share_tw_right" />';
	soc_v_left  = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Tumblr.png" class="share_vk" id="share_vk_left" />';
	soc_v_right = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Tumblr.png" class="share_vk" id="share_vk_right" />';	

    //Init popover events. 
    init_popover();		
    //Run popover events
	$(".voiceclass").click(function(){

		switch ( $(this).attr("id") ) {
		  case "voice_left":
		  	placement_var = 'left';
			$(this).popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: placement_var ,
							content: soc_v_left+soc_t_left+soc_f_left });		  	
		  	$("#voice_right").popover('destroy');
			$("#voice_right").popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: 'right' ,
							content: soc_v_right+soc_t_right+soc_f_right });		  	
		  break
		  default :
		    placement_var = 'right';
		    $(this).popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: placement_var ,
							content: soc_v_right+soc_t_right+soc_f_right });
		    $("#voice_left").popover('destroy');
		    $("#voice_left").popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: 'left' ,
							content: soc_v_left+soc_t_left+soc_f_left });
  		  break	
		}
	})

	$('.share_vk').live("click",function(){
		if ($(this).attr("id") == "share_vk_left") {
		  	vkontakte_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		  	vkontakte_obj.elem_view= $('#vk_lot_left');
		} else {
			vkontakte_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
			vkontakte_obj.elem_view= $('#vk_lot_right');
		}
		vkontakte_obj.share();
		var timer = setInterval(function () {
 		    if (win.closed){
 		      vkontakte_obj.getCountShare();
 		      setTimeout(function(){ 
 		      clearInterval(timer);
 		      win = null;
 		    } , 10);
 		  }
 		}, 20);
 	});

	$('.share_tw').live("click",function(){
		if ($(this).attr("id") == "share_tw_left") {
		  	twitter_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		  	twitter_obj.elem_view= $('#tw_lot_left');
		} else {
			twitter_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
			twitter_obj.elem_view= $('#tw_lot_right');
		}
		twitter_obj.share();
		var timer = setInterval(function () {
 		    if (win.closed){
 		      twitter_obj.getCountShare();
 		      setTimeout(function(){ 
 		      clearInterval(timer);
 		      win = null;
 		    } , 10);
 		  }
 		}, 20);
 	});

	$('.share_fb').live("click",function(){
		if ($(this).attr("id") == "share_fb_left") {
		  	facebook_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		  	facebook_obj.elem_view= $('#fb_lot_left');
		} else {
			facebook_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
			facebook_obj.elem_view= $('#fb_lot_right');
		}
		facebook_obj.share();
		var timer = setInterval(function () {
 		    if (win.closed){
 		      facebook_obj.getCountShare();
 		      setTimeout(function(){ 
 		      clearInterval(timer);
 		      win = null;
 		    } , 10);
 		  }
 		}, 20);
 	}); 	

   
 	$('#b2').tooltip({ html: 'true', 
 					   title: '<p class="my_line desc_wrap mywrap"><%= description2 %></p>', 
					   placement: 'right'});
 	$('#b1').tooltip({  title: '<p class="my_line desc_wrap mywrap"><%= description1 %></p>', 
						html: 'true', 
						placement: 'left',
						trigger: 'hover' }	)

 	

});


</script>

app/views/shared/_head_script_social_vote_strip.html.erb
<script>


vkontakte_obj.shares_url = "<%= shares_url %>";
facebook_obj.shares_url  = "<%= shares_url %>";
twitter_obj.shares_url   = "<%= shares_url %>";
//Секция инициализации


$(function(){
	vkontakte_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );	
	twitter_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );
	facebook_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );

		

	$('.share_vk').live("click",function(){
		if ($(this).attr("id") == "share_vk_left") {
		  	vkontakte_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		    vkontakte_obj.change_params('','','','<%= "#{desc_left}" %>' );
		} else {
			vkontakte_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
		    vkontakte_obj.change_params('','','','<%= "#{desc_right}" %>' );		    
		}
		vkontakte_obj.share();
 	});

	$('.share_tw').live("click",function(){
		if ($(this).attr("id") == "share_tw_left") {
		  	twitter_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		    twitter_obj.change_params('','','','<%= "#{desc_left}" %>' );		  	
		} else {
			twitter_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
		    twitter_obj.change_params('','','','<%= "#{desc_right}" %>' );				
		}
		twitter_obj.share();
 	});

	$('.share_fb').live("click",function(){
		if ($(this).attr("id") == "share_fb_left") {
		  	facebook_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		    facebook_obj.change_params('','','','<%= "#{desc_left}" %>' );		  	
		} else {
			facebook_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
		    facebook_obj.change_params('','','','<%= "#{desc_right}" %>' );				
		}
		facebook_obj.share();
 	}); 	

   
 	$('#b2').tooltip({ html: 'true', 
 					   title: '<p class="my_line desc_wrap mywrap"><%= description2 %></p>', 
					   placement: 'right'});
 	$('#b1').tooltip({  title: '<p class="my_line desc_wrap mywrap"><%= description1 %></p>', 
						html: 'true', 
						placement: 'left',
						trigger: 'hover' }	)
});


</script>

app/views/shared/_header.html.erb
<%
# named block
page_general = "Битва"
page_lists = "Список"
page_feedback = "Отзыв"
page_admin = "Админка"
%>

<div class="container-narrow-header">
<div class="navbar">
  <div class="navbar-inner ">

    <div style="text-align:center">
      <ul class="nav">
        <li <% if current_page? Buttle.in_general_page.nil? ? root_path : buttle_path(Buttle.in_general_page.id) %> class="active" <% end %> >
        	<%= link_to(page_general, root_path) %>
        </li>
        <!--  <li class="divider-vertical"></li> -->
        <li <% if current_page? buttles_path %> class="active" <% end %> > 
        	<%= link_to(page_lists, buttles_path) %>
        </li>
        <!-- <li class="divider-vertical"></li>  -->
        <li  <% if current_page? new_feedback_path %> class="active" <% end %> >
        	<%= link_to(page_feedback, new_feedback_path) %>
        </li>
        <!-- <li class="divider-vertical"></li> -->
        <% if Rails.env.development? %>
        <li  <% if current_page? myadmin_path %> class="active" <% end %> >
          <%= link_to(page_admin, myadmin_path) %>
        </li>        
        <% end %>
      </ul>
    </div>
    <a class="brand" href="#" style="float:right">Орлиные битвы</a>
  </div>
</div>
</div>

app/views/shared/копия _head_script_social_vote.html.erb
<script>


vkontakte_obj.shares_url = "<%= shares_url %>";
facebook_obj.shares_url  = "<%= shares_url %>";
twitter_obj.shares_url   = "<%= shares_url %>";
//Секция инициализации

function init_popover() {

  $("#voice_left").popover({ title: 'Воспользуйтесь соц.сетью', 
  				html: 'true', 
  				placement: 'left' ,
  				content: soc_v_left+soc_t_left+soc_f_left });	
  
  $("#voice_right").popover({ title: 'Воспользуйтесь соц.сетью', 
  				html: 'true', 
  				placement: 'right' ,
  				content: soc_v_right+soc_t_right+soc_f_right });	

}


$(function(){
	vkontakte_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );	

	vkontakte_obj.elem_view= $('#vk_lot_left');

	twitter_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );

	twitter_obj.elem_view= $('#tw_lot_left');	

	facebook_obj.make_params(
			'<%= "#{shares_url}" %>',
			'<%= "#{title}" %>',
			'<%= "#{image_voice_left}" %>',
			'<%= "#{desc}" %>' );

	facebook_obj.elem_view= $('#fb_lot_left');	


	soc_f_left = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Facebook.png"  class="share_fb" id="share_fb_left" />';
	soc_f_right = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Facebook.png" class="share_fb" id="share_fb_right" />';
	soc_t_left  = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Twitter.png" class="share_tw" id="share_tw_left" />';
	soc_t_right = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Twitter.png" class="share_tw" id="share_tw_right" />';
	soc_v_left  = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Tumblr.png" class="share_vk" id="share_vk_left" />';
	soc_v_right = '<img src="http://<%= APP_CONFIG['site_domain'] %>:<%= APP_CONFIG['site_port'] %>/assets/decor/Tumblr.png" class="share_vk" id="share_vk_right" />';	

    //Init popover events. 
    init_popover();		
    //Run popover events
	$(".voiceclass").click(function(){

		switch ( $(this).attr("id") ) {
		  case "voice_left":
		  	placement_var = 'left';
			$(this).popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: placement_var ,
							content: soc_v_left+soc_t_left+soc_f_left });		  	
		  	$("#voice_right").popover('destroy');
			$("#voice_right").popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: 'right' ,
							content: soc_v_right+soc_t_right+soc_f_right });		  	
		  break
		  default :
		    placement_var = 'right';
		    $(this).popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: placement_var ,
							content: soc_v_right+soc_t_right+soc_f_right });
		    $("#voice_left").popover('destroy');
		    $("#voice_left").popover({ title: 'Воспользуйтесь соц.сетью', 
							html: 'true', 
							placement: 'left' ,
							content: soc_v_left+soc_t_left+soc_f_left });
  		  break	
		}
	})

	$('.share_vk').live("click",function(){
		if ($(this).attr("id") == "share_vk_left") {
		  	vkontakte_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		  	vkontakte_obj.elem_view= $('#vk_lot_left');
		} else {
			vkontakte_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
			vkontakte_obj.elem_view= $('#vk_lot_right');
		}
		vkontakte_obj.share();
		var timer = setInterval(function () {
 		    if (win.closed){
 		      vkontakte_obj.getCountShare();
 		      setTimeout(function(){ 
 		      clearInterval(timer);
 		      win = null;
 		    } , 10);
 		  }
 		}, 20);
 	});

	$('.share_tw').live("click",function(){
		if ($(this).attr("id") == "share_tw_left") {
		  	twitter_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		  	twitter_obj.elem_view= $('#tw_lot_left');
		} else {
			twitter_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
			twitter_obj.elem_view= $('#tw_lot_right');
		}
		twitter_obj.share();
		var timer = setInterval(function () {
 		    if (win.closed){
 		      twitter_obj.getCountShare();
 		      setTimeout(function(){ 
 		      clearInterval(timer);
 		      win = null;
 		    } , 10);
 		  }
 		}, 20);
 	});

	$('.share_fb').live("click",function(){
		if ($(this).attr("id") == "share_fb_left") {
		  	facebook_obj.change_params('','','<%= "#{image_voice_left}" %>','' );
		  	facebook_obj.elem_view= $('#fb_lot_left');
		} else {
			facebook_obj.change_params('','','<%= "#{image_voice_right}" %>','' );
			facebook_obj.elem_view= $('#fb_lot_right');
		}
		facebook_obj.share();
		var timer = setInterval(function () {
 		    if (win.closed){
 		      facebook_obj.getCountShare();
 		      setTimeout(function(){ 
 		      clearInterval(timer);
 		      win = null;
 		    } , 10);
 		  }
 		}, 20);
 	}); 	

   
 	$('#b2').tooltip({ html: 'true', 
 					   title: '<p class="my_line desc_wrap mywrap"><%= description2 %></p>', 
					   placement: 'right'});
 	$('#b1').tooltip({  title: '<p class="my_line desc_wrap mywrap"><%= description1 %></p>', 
						html: 'true', 
						placement: 'left',
						trigger: 'hover' }	)

 	

});


</script>