config/routes.rb
Battle::Application.routes.draw do
  
  

  resources :feedbacks, :only => [:new, :create] do
    collection do
      get :thank_you
    end  
  end  

  class ForRedirectFromGeneralPage 
    def self.matches?(request)
      return false unless Buttle.where(:published => true).first;
      return true
    end  
  end  
  constraints ForRedirectFromGeneralPage do
    match "/" => redirect {| p,request | "/buttles/#{Buttle.in_general_page.id}" }
  end  
  match "/" => "buttles#index"

  resources :buttles  

  namespace :myadmin do
    match "/" => "index#index"
    resources :buttles
    resources :feedbacks do
      member do 
        post :to_read_message
      end  
      collection do
        get :massmove
      end  
    end  

    resources :lots do
      collection do       
        get :one_lot
      end
      member do 
      end  
    end  

    resources :options do
      member do
        post :quick_update
      end  
      collection do
        get :massmove
      end  
    end  

    get '/votes' => 'votes#all'

  end  #myadmin
      

  resources :votes, :only => :new  
    
  match "/home", :to => "pages#home"
  

  root :to => "pages#home"

end

app/controllers/buttles_controller.rb
#encoding: utf-8
require 'stamp'

require 'new_will_paginate'

class ButtlesController < ApplicationController
  # GET /buttles
  # GET /buttles.json
  def index

    @buttles = Buttle.paginate(:page => params[:page] || 1, :per_page => 3)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buttles }
    end
  end

  # GET /buttles/1
  # GET /buttles/1.json
  def show
    @buttle = Buttle.find(params[:id])

    @title = 'Home page'
    cookies[:battle] = Time.now
   # @buttle = Buttle.first
    
    @border_div = 0

    @description1 =  @buttle.opponent_first.description.to_s.squish
    @description2 =  @buttle.opponent_second.description.to_s.squish

    @description1_for_share =  "1"#{}"По-моему круче: #{@buttle.opponent_first.name}"
    @description2_for_share =  "2"#{}"По-моему круче: #{@buttle.opponent_second.name}"    
  
    @desc = "Simple test text"
    @desc_left = "#{@buttle.name}. Мой выбор: #{@buttle.opponent_first.name}"
    @desc_right = "#{@buttle.name}. Мой выбор: #{@buttle.opponent_second.name}"


    @count_voite_left = @buttle.votes_first_opponent.size
    @count_voite_right = @buttle.votes_second_opponent.size

    @shares_url = "http://qwertytestytrewq.ru/privet/4"#request.url#
    @title = "Битвы Орла"#@buttle.name 
    @image_path_vk = "http://localhost:3000/assets/decor/logo.jpg"
 
    @image_voice_left = "http://#{request.host}:#{request.port}#{@buttle.opponent_first.image.url(:small)}"
    @image_voice_right = "http://#{request.host}:#{request.port}#{@buttle.opponent_second.image.url(:small)}"
    
    
    #OUT_BECAUSE_DRY
    if consider_ip_set = Option.find_by_param("consider_ip")
      @guest_ip = consider_ip_set.value == "true" ? request.remote_ip.to_s : "127.0.0.2"  
    else
      @guest_ip = APP_CONFIG['consider_ip'] == "true" ? request.remote_ip.to_s : "127.0.0.2"  
    end  
 
    @vote_access_left =  @buttle.access_vote_first_opponent(@guest_ip)
    @vote_access_right = @buttle.access_vote_second_opponent(@guest_ip)
 
    @vote_access = @buttle.access_vote(@guest_ip)
    


    


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buttle }
    end
  end

  # GET /buttles/new
  # GET /buttles/new.json
  def new
    @buttle = Buttle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buttle }
    end
  end

  # GET /buttles/1/edit
  def edit
    @buttle = Buttle.find(params[:id])
    @lots = Lot.all
  end

  # POST /buttles
  # POST /buttles.json
  def create
    @buttle = Buttle.new(params[:buttle])

    respond_to do |format|
      if @buttle.save
        format.html { redirect_to buttles_path, notice: 'Buttle was successfully created.' }
        format.json { render json: @buttle, status: :created, location: @buttle }
      else
        format.html { render action: "new" }
        format.json { render json: @buttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buttles/1
  # PUT /buttles/1.json
  def update
    @buttle = Buttle.find(params[:id])

    respond_to do |format|
      if @buttle.update_attributes(params[:buttle])
        format.html { redirect_to buttles_path, notice: 'Buttle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buttles/1
  # DELETE /buttles/1.json
  def destroy
    @buttle = Buttle.find(params[:id])
    @buttle.destroy

    respond_to do |format|
      format.html { redirect_to buttles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/application_controller.rb
class Myadmin::ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate#:check_access
  layout 'myadmin'



  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      md5_of_password = Digest::MD5.hexdigest(password)
      username == 'admin' && password == 'admin'#md5_of_password == 'a86838dae048198de7487400d109bfd3'
    end  	
  end	
  #def check_access
  #	true
  #end	
end

app/controllers/myadmin/buttles_controller.rb
class Myadmin::ButtlesController < Myadmin::ApplicationController
  # GET /buttles
  # GET /buttles.json
  def index
    @buttles = Buttle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buttles }
    end
  end

  # GET /buttles/1
  # GET /buttles/1.json
  def show
    @buttle = Buttle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buttle }
    end
  end

  # GET /buttles/new
  # GET /buttles/new.json
  def new
    @buttle = Buttle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buttle }
    end
  end

  # GET /buttles/1/edit
  def edit
    @buttle = Buttle.find(params[:id])
    @lots = Lot.all
  end

  # POST /buttles
  # POST /buttles.json
  def create
    @buttle = Buttle.new(params[:buttle])

    respond_to do |format|
      if @buttle.save
        format.html { redirect_to myadmin_buttles_path, notice: 'Buttle was successfully created.' }
        format.json { render json: @buttle, status: :created, location: @buttle }
      else
        format.html { render action: "new" }
        format.json { render json: @buttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buttles/1
  # PUT /buttles/1.json
  def update
    @buttle = Buttle.find(params[:id])

    respond_to do |format|
      if @buttle.update_attributes(params[:buttle])
        format.html { redirect_to myadmin_buttles_path, notice: 'Buttle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buttles/1
  # DELETE /buttles/1.json
  def destroy
    @buttle = Buttle.find(params[:id])
    @buttle.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_buttles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/feedbacks_controller.rb
class Myadmin::FeedbacksController < Myadmin::ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    #@feedbacks = Feedback.all
    @feedbacks = Feedback.no_read

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  def thank_you
    #@feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end  

  def to_read_message
    feedback_item = Feedback.find(params[:id])
    feedback_item.update_attribute(:read, true)
    render :json => {:result => "ok"}
  end

  def massmove
    Feedback.all.map{|item|item.update_attribute(:read, true)} if params[:move] == "read"
    Feedback.all.map{|item|item.update_attribute(:read, false)} if params[:move] == "not_read"

    respond_to do |format|
      format.html { redirect_to myadmin_feedbacks_url}
    end  

  end  

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to myadmin_thank_you_feedbacks_path, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/index_controller.rb
class Myadmin::IndexController < Myadmin::ApplicationController
  def index

  end	


end	

app/controllers/myadmin/lots_controller.rb
class Myadmin::LotsController < Myadmin::ApplicationController
  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lots }
    end
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @lot }
    end
  end

  # GET /lots/new
  # GET /lots/new.json
  def new
    @lot = Lot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @lot }
    end
  end

  # GET /lots/1/edit
  def edit
    @lot = Lot.find(params[:id])
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(params[:lot])

    respond_to do |format|
      if @lot.save
        format.html { redirect_to myadmin_lots_path, :notice => 'Lot was successfully created.' }
        format.json { render :json => @lot, :status => :created, :location => @lot }
      else
        format.html { render :action => "new" }
        format.json { render :json => @lot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lots/1
  # PUT /lots/1.json
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to myadmin_lots_path, :notice => 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @lot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_lots_url }
      format.json { head :no_content }
    end
  end

  def one_lot
    @lots = Lot.all
    @opponent_number = params[:opponent]
    respond_to do |format|
      format.html {}
      format.js {}
    end  
  end  

end

app/controllers/myadmin/options_controller.rb
class Myadmin::OptionsController < Myadmin::ApplicationController
  # GET /options
  # GET /options.json
  def index
    @options = Option.all
    @ip = request.remote_ip
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /options/1/quick_update
  def quick_update
    @option = Option.find_by_id(params[:id])
    if @option
      @option.update_attributes(params[:option])
    else
      @option = Option.create(params[:option])   
    end  


    respond_to do |format|
      if @option
        format.json { render json: @option.id }        
      else
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end  
    end      


  end  


  def massmove
    if params[:move] == "delete"
      Option.delete_all
      respond_to do |format| 
        format.html {redirect_to myadmin_options_path }
      end  
    end  
  end  

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to myadmin_options_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/myadmin/votes_controller.rb
class Myadmin::VotesController < Myadmin::ApplicationController

  def all

    @all_votes = Vote.all
    respond_to do |format|
      format.html
    end  

  end  

end	

app/helpers/buttles_helper.rb
module ButtlesHelper
end

app/views/myadmin/buttles/_form.html.erb
  <div id="ajax_form_season"></div>



<div class="row-fluid center-elem">
<%= form_for(@buttle, :url => @buttle.new_record? ? myadmin_buttles_path : myadmin_buttle_path,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @buttle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buttle.errors.count, "error") %> prohibited this buttle from being saved:</h2>

      <ul>
      <% @buttle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<div class="control-group">
  <div class="control-label">Название битвы </div>
  <div class="controls">
    <%= f.text_field :name %>
  </div>  
</div>  

<div class="control-group">
  <div class="control-label">Описание битвы </div>
  <div class="controls">
    <%= f.text_area :description %>
  </div>  
</div> 

<div class="control-group">
  <div class="control-label">На главной? </div>
  <div class="controls">
    <%= f.check_box :published %>
  </div>  
</div> 

<div class="control-group">
  <div class="control-label">Оппонент 1 </div>
  <div class="controls">
    <span id="img_after_ajax_1">
      <% unless @buttle.new_record? %>
      <%= image_tag(@buttle.opponent_first.image.url(:small)) if  @buttle.try(:opponent_first)   %>
      <% end %> 
    </span>
    <%= f.hidden_field :opponent_1, :id => "after_ajax_1"   %>
    <%= link_to  "Выбрать лот 1", one_lot_myadmin_lots_path(:opponent => 1), :remote => true, :class => "btn" %>
  </div>  
</div> 

<div class="control-group">
  <div class="control-label">Оппонент 2 </div>
  <div class="controls">
    <span id="img_after_ajax_2">
      <% unless @buttle.new_record? %>      
        <%= image_tag(@buttle.opponent_second.image.url(:small)) if  @buttle.try(:opponent_second)  %>
      <% end %>  
    </span><%= f.hidden_field :opponent_2, :id => "after_ajax_2"   %>
    <%= link_to  "Выбрать лот 2", one_lot_myadmin_lots_path(:opponent => 2), :remote => true, :class => "btn" %>
  </div>  
</div> 



<div class="actions">
  <%= f.submit @buttle.new_record? ? "Создать" : "Отредактировать",:class => "btn" %>
</div>
<% end %>
</div>

app/views/myadmin/buttles/edit.html.erb
<div class="row-fluid center-elem">
<h1>Редактировать битву</h1><br/>
</div>

<%= render 'form' %>

<%#= link_to 'Show', @buttle %> |
<%#= link_to 'Back', myadmin_buttles_path %>

app/views/myadmin/buttles/index.html.erb
<%#= render :partial => 'shared/admin_head' %>
<div class="row-fluid center-elem update_big_elem">
    <h1>Битвы</h1>  
</div>    
<div>
<div class="row-fluid center-elem">


<table class="table table-striped " > <!-- класс сетки для таблицы table-bordered -->
  <tr>
    <th>Имя</th>
    <th>
      <div class="center-elem">
        Описание
      </div>
    </th>
    <th>Первый оппонент</th>
    <th>Второй оппонент</th>        
    <th>На главной</th>
    <th></th>
    <th></th>
  </tr>

<% @buttles.each do |buttle| %>
  <tr>
    <td >
      <p class="name_wrap mywrap">
        <%= buttle.name %>
      </p>
    </td>
    <td >
      <p class="desc_wrap mywrap">      
          <small><%= buttle.description %></small>
      </p>    
    </td>

    <td>
      <div class="center-elem">
        <%= image_tag buttle.opponent_first.image(:small) if buttle.opponent_first  %>
      </div>
    </td>
    <td>
      <div class="center-elem">
        <%= image_tag buttle.opponent_second.image(:small) if buttle.opponent_second %>
      </div>
    </td>
    <td>
      <div class="center-elem">
        <%= buttle.published? ? "Да" : "Нет" %>
      </div>
    </td>        

    <td><%= link_to 'Редактировать', edit_myadmin_buttle_path(buttle), :class=>"btn btn-warning " %></td>
    <td><%= link_to 'Удалить', myadmin_buttle_path(buttle), :method => :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>

  

<br />

<%= link_to 'Новая битва', new_myadmin_buttle_path, :class => "btn btn-large btn-simple" %>
</div>

app/views/myadmin/buttles/new.html.erb
<div class="row-fluid center-elem">
<h1>Новая битва</h1>

<%= render 'form' %>

<%#= link_to 'Back', myadmin_buttles_path %>
</div>

app/views/myadmin/buttles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_myadmin_buttle_path(@buttle) %> |
<%= link_to 'Back', myadmin_buttles_path %>